---
arturl_encode: "68747470733a2f2f62:6c6f672e6373646e2e6e65742f71715f34343736383832332f:61727469636c652f64657461696c732f313038343834383539"
layout: post
title: "Centos安装python遇到ln-failed-to-create-symbolic-link-usrbinpython-File-exists"
date: 2024-04-07 18:20:14 +08:00
description: "创建软连接的时候ln -s /usr/local/python3.6/bin/python3.6 /"
keywords: "ln 无法创建符号链接 failed to create symbolic link"
categories: ['未分类']
tags: ['无标签']
artid: "108484859"
image:
  path: https://api.vvhan.com/api/bing?rand=sj&artid=108484859
  alt: "Centos安装python遇到ln-failed-to-create-symbolic-link-usrbinpython-File-exists"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=108484859
featuredImagePreview: https://bing.ee123.net/img/rand?artid=108484859
---

# Centos安装python遇到ln: failed to create symbolic link ‘/usr/bin/python’: File exists

创建软连接的时候
  
ln -s /usr/local/python3.6/bin/python3.6 /usr/bin/python
  
报错

意思就是说文件已经存在

使用ln -sf /usr/local/python3.6/bin/python3.6 /usr/bin/python
  
ln -sf 覆盖原来的文件