---
arturl_encode: "68747470733a2f:2f626c6f672e6373646e2e6e65742f6c75636b797775786e2f:61727469636c652f64657461696c732f313436313031333239"
layout: post
title: "python-APScheduler插件部署服务器报错问题"
date: 2025-03-07 17:48:45 +0800
description: "后面想起来可能是版本兼容问题，我用的python是3.12 我查了他对应的 openssl版本应该是1.1以上，我查了一下我当前的版本是1.0。于是我开始升级openssl的版本，可是无论我怎么升也还是1.0，后面才发现我的服务器版本是centos7 他对应的openssl就是1.0。特此记录，若能帮到遇到同样问题的小伙伴，也算是没有白费我这几分钟写下此博文。deepseek一直提示安装openssl,我检查openssl是有的，使用以下命令装了几次也还是一样。"
keywords: "python APScheduler插件部署服务器报错问题"
categories: ['Python']
tags: ['服务器', 'Python', 'Github']
artid: "146101329"
image:
    path: https://api.vvhan.com/api/bing?rand=sj&artid=146101329
    alt: "python-APScheduler插件部署服务器报错问题"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=146101329
featuredImagePreview: https://bing.ee123.net/img/rand?artid=146101329
cover: https://bing.ee123.net/img/rand?artid=146101329
image: https://bing.ee123.net/img/rand?artid=146101329
img: https://bing.ee123.net/img/rand?artid=146101329
---

# python APScheduler插件部署服务器报错问题

今天我在使用python测试定时任务部署到服务器的时候，一直报下面的错误。

```javascript
Job "send_wechat_webhook (trigger: cron[second='*/2'], next run at: 2025-03-07 12:00:12 CST)" raised an exception Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 131, in run_job retval = job.func(*job.args, **job.kwargs) 
File "/home/ap/stock-task/schedulers/stock.py", line 15, in send_wechat_webhook response = requests.post(webhook_url, data=json.dumps(data), headers=headers)
File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send resp = conn.urlopen( 
File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 766, in urlopen conn = self._get_conn(timeout=pool_timeout)
File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 292, in _get_conn return conn or self._new_conn()
File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1057, in _new_conn raise ImportError( ImportError: Can't connect to HTTPS URL because the SSL module is not available.

```

deepseek一直提示安装openssl,我检查openssl是有的，使用以下命令装了几次也还是一样

```javascript
sudo ./configure --enable-optimizations --with-openssl=/usr --with-ssl-default-suites=openssl

```

后面想起来可能是版本兼容问题，我用的python是3.12 我查了他对应的 openssl版本应该是1.1以上，我查了一下我当前的版本是1.0。于是我开始升级openssl的版本，可是无论我怎么升也还是1.0，后面才发现我的服务器版本是centos7 他对应的openssl就是1.0。于是我手动升级openssl到1.1 ，然后发现问题就解决了。特此记录，若能帮到遇到同样问题的小伙伴，也算是没有白费我这几分钟写下此博文。