---
arturl_encode: "68747470733a2f2f62:6c6f672e6373646e2e6e65742f6d305f33373133353631352f:61727469636c652f64657461696c732f313436313434383136"
layout: post
title: "测试框架篇单元测试框架pytest4assert断言详解"
date: 2025-03-10 09:55:52 +08:00
description: "就是对预期结果的断言。何为断言？简单来说就是实际结果和期望结果去对比，符合预期就测试pass，不符合预期那就测试 failed。断言内容就是你要的预期结果。断言包含对接口响应内容做断言、也包含对落DB的数据做断言。pytest可以让。"
keywords: "【测试框架篇】单元测试框架pytest（4）：assert断言详解"
categories: ['测试框架']
tags: ['单元测试', 'Pytest']
artid: "146144816"
image:
    path: https://api.vvhan.com/api/bing?rand=sj&artid=146144816
    alt: "测试框架篇单元测试框架pytest4assert断言详解"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=146144816
featuredImagePreview: https://bing.ee123.net/img/rand?artid=146144816
cover: https://bing.ee123.net/img/rand?artid=146144816
image: https://bing.ee123.net/img/rand?artid=146144816
img: https://bing.ee123.net/img/rand?artid=146144816
---

# 【测试框架篇】单元测试框架pytest（4）：assert断言详解

## **一、前言**

**用例三要素之一**
就是对预期结果的断言。

何为断言？简单来说就是实际结果和期望结果去对比，符合预期就测试pass，不符合预期那就测试 failed。断言内容就是你要的预期结果。断言包含对接口响应内容做断言、也包含对落DB的数据做断言。

pytest可以让
[开发者](https://zhida.zhihu.com/search?content_id=172632527&content_type=Article&match_order=1&q=%E5%BC%80%E5%8F%91%E8%80%85&zhida_source=entity "开发者")
使用Python断言来验证测试中的期望值。

话不多说，我们来举个小例子熟悉一下，一般我们会在抛出异常之后输出一些提示信息，执行之后就方便查看是什么原因了。

```python
# 异常信息
def f():
    return 3
def test_function():
    a = f()
    assert a % 2 == 0, "判断 a 为偶数，当前 a 的值为：%s" % a
```

### 执行结果

[![](https://i-blog.csdnimg.cn/img_convert/213319fed7c86a44a9c52857a7fceb6d.png)](https://img2020.cnblogs.com/blog/1896874/202004/1896874-20200406130902312-172338387.png)

## 二、常用断言

pytest 里面断言实际上就是 python 里面的 assert 断言方法，常用的有以下几种

* assert xx ：判断 xx 为真
* assert not xx ：判断 xx 不为真
* assert a in b ：判断 b 包含 a
* assert a == b ：判断 a 等于 b
* assert a != b ：判断 a 不等于 b

## 三、异常断言

可以使用 pytest.raises 作为上下文管理器，当抛出异常时可以获取到对应的异常实例

```python
# 断言异常
def test_zero_division():
    with pytest.raises(ZeroDivisionError):
        1 / 0
```

**断言场景：**
断言它抛的异常是不是预期想要的

**代码执行：**
1/0

**预期结果：**
抛的异常是ZeroDivisionError: division by zero

**如何断言：**
通常是断言异常的 type 和 value 值了

**具体方式：**
这里 1/0 的异常类型是 ZeroDivisionError，异常的 value 值是 divisionby zero

```python
#详细断言异常
def test_zero_division_long():
    with pytest.raises(ZeroDivisionError) as excinfo:
        1 / 0

    # 断言异常类型 type
    assert excinfo.type == ZeroDivisionError
    # 断言异常 value 值
    assert "division by zero" in str(excinfo.value)
```

excinfo ：是一个异常信息实例

**主要属性：**
.type 、  .value 、 .traceback

**注意：**
断言 type 的时候，异常类型是不需要加引号的，断言 value值的时候需转 str

## 拓展一：match

可以将 match 关键字参数传递给上下文管理器，以测试正则表达式与异常的字符串表示形式是否匹配

**注意：**
这种方法只能断言value，不能断言type

```python
# 自定义消息
def test_zero_division_long():
    with pytest.raises(ZeroDivisionError, match=".*zero.*") as excinfo:
        1 / 0
```

该 match 方法的regexp参数与 re.search  函数匹配，因此在上面的示例中 match='zero' 也可以使用

[![](https://i-blog.csdnimg.cn/img_convert/11a8284d2b73af32477bded112c6f552.png)](https://img2020.cnblogs.com/blog/1896874/202004/1896874-20200406135355943-1838438116.png)

[![](https://i-blog.csdnimg.cn/img_convert/3bc9d4bee5cd88f4c6723961f125e42a.png)](https://img2020.cnblogs.com/blog/1896874/202004/1896874-20200406135407511-1382697695.png)

## 拓展二：检查断言装饰器

```python
# 断言装饰器
@pytest.mark.xfail(raises=ZeroDivisionError)
def test_f():
    1 / 0
```

### 执行结果

[![](https://i-blog.csdnimg.cn/img_convert/b46b5ecee3c0bf298e61994555ffbe0c.png)](https://img2020.cnblogs.com/blog/1896874/202004/1896874-20200406140623462-429848886.png)

### 知识点

* 代码抛出异常，但是和raises指定的异常类相匹配，所以不会断言失败
* 它相当于一个
  **检查异常装饰器**
  **，功能：**
  检查是否有异常，不确定是否有异常
* with pytest.raise(ZeroDivisionError)  对于故意测试异常代码的情况，使用可能会更好
* `而@pytest.mark.xfail(raises=ZeroDivisionError)`
  对于检查未修复的错误（即，可能会发生异常），使用检查断言可能会更好